# Finetune LatentWorldVLA on LIBERO, latent + perceptual

# Base model & LAM
model_cfg:
  model_id: "/mnt/project_rlinf/jlchen/code/UniVLA/vla_scripts/vla_log/0111_000540+vla_emb_unfreeze_llm4_dec_gt_no_history_no_distill/checkpoints/checkpoint-90000"
  lam_ckpt_path: "/mnt/project_rlinf/jlchen/code/UniVLA/latent_action_model/logs/dino_base_ae_bigwin/version_0/checkpoints/epoch=21.ckpt"
  lam_yaml_path: "/mnt/project_rlinf/jlchen/code/UniVLA/latent_action_model/logs/dino_base_ae_bigwin/version_0/dino_base_ae.yaml"
  perceptual_weight: 0.3
  # 细粒度冻结策略（替代原有的 freeze_vlm）
  freeze_vision_backbone: true      # 冻结视觉骨干
  freeze_llm_backbone: true         # 冻结语言模型骨干
  freeze_last_llm_layer: true      # 保持 LM head 可训练
  freeze_embedding: true           # 保持嵌入层可训练
  unfreeze_vision_merger: true     # 不解冻视觉 merger
  unfreeze_llm_last_n_layers: 4 # 不解冻最后 N 层（设为数字如 4 可解冻最后4层）
  unfreeze_lam_decoder: true
  latent_action_placeholder_token: "<ACT_PH>"

# Dataset & preprocessing
data_root_dir: "/mnt/project_rlinf/jlchen/datasets"
data_mix: "libero_object_no_noops"
image_resolution: 256
shuffle_buffer_size: 2000
image_aug: false
use_history_frame: false

debug_repeat_batch: false


# Optimization
batch_size: 32
max_steps: 40000
save_steps: 2000
eval_steps: 1000
eval_batches: 100
learning_rate: 1.0e-4
warmup_steps: 0
vlm_learning_rate: 1.0e-5
vlm_warmup_steps: 200
grad_accumulation_steps: 2
gradient_clip: 1.0
weight_decay: 1.0e-4
# vlm_loss_weight: 1.0
seed: 42

# Logging / run id
run_id_note: "finetune_test"
wandb_project: "finetune-LIBERO"
wandb_entity: null
