

# Hugging Face 模型（本地路径或 HF Hub ID）
# model_id: "/mnt/mnt/public/jlchen/weights/InternVL3_5-1B-Instruct-HF"
model_id: "/mnt/mnt/public/jlchen/weights/Qwen3-VL-2B-Instruct"
# lam_ckpt_path: str="/mnt/mnt/public/jlchen/code/UniVLA/latent_action_model/logs/dino_base_4q_32_crossattn_mask_2f_norep_bn/version_1/checkpoints/epoch=19.ckpt"
# lam_yaml_path: str="/mnt/mnt/public/jlchen/code/UniVLA/latent_action_model/logs/dino_base_4q_32_crossattn_mask_2f_norep_bn/version_1/dino_base_2f.yaml"
lam_ckpt_path: "/mnt/mnt/public/jlchen/code/UniVLA/latent_action_model/logs/dino_base_4q_32_norep/version_0/checkpoints/epoch=4.ckpt"
lam_yaml_path: "/mnt/mnt/public/jlchen/code/UniVLA/latent_action_model/logs/dino_base_4q_32_norep/version_0/dino_base.yaml"
# 数据与预处理
data_mix: lam_plus


# 训练超参
training_phase: lam_2f
per_device_batch_size: 128
gradient_accumulation_steps: 1
learning_rate: 1e-3
act_query_lr_scale: 5.0
vlm_to_lam_lr_scale: 5.0
warmup_steps: 0
use_history_frame: true

# 运行与日志
run_id: vla_lora_hist

enable_lora: true
freeze_vision_backbone: true
freeze_llm_backbone: false
freeze_last_llm_layer: false
freeze_projector: false
freeze_llm_first_n_layers: false

