
import torch
import math
import torch.nn.functional as F
import torch.nn as nn

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        lower = norm_cdf((a - mean) / std)
        upper = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [lower, upper], then translate to
        # [2*lower-1, 2*upper-1].
        tensor.uniform_(2 * lower - 1, 2 * upper - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.0))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0.0, std=1.0, a=-2.0, b=2.0):
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

def eef_reconstruction_loss(
    state: torch.Tensor,
    s_pred: torch.Tensor,
    pos_loss_type: str = "l1",
    reduction: str = "mean",
) -> torch.Tensor:
    """
    计算末帧 EEF 状态的重建损失（位置 + 朝向 + 抓手开合）。
    
    Args:
        state: 实际状态 (..., T, 8)
        s_pred: 预测状态 (..., 8)
        loss_type: 'l1' 或 'l2'
        reduction: 'mean' | 'sum' | 'none'
    """
    if len(s_pred.shape)==2:
        s_pred = s_pred.unsqueeze(1)
    # --- 提取末帧 ---
    state_gt = state[..., -s_pred.shape[1]:, :]       # (..., 8)
    # 兼容输入形状：允许 s_pred 为 (..., 8) 或 (..., 1, 8)

    # --- 拆分状态分量 ---
    pos_ori_target = state_gt[..., :-1]   # 位置 + 朝向 (7维)
    gripper_target = (state_gt[..., -1:] > 0.0).float()  # 抓手状态 (1维)

    pos_ori_pred = s_pred[..., :-1]
    gripper_pred = s_pred[..., -1:]

    # --- 计算位置 + 朝向损失 ---
    if pos_loss_type == "l1":
        pos_ori_loss = torch.abs(pos_ori_pred - pos_ori_target)
    elif pos_loss_type == "l2":
        pos_ori_loss = (pos_ori_pred - pos_ori_target) ** 2
    else:
        raise ValueError(f"Unsupported pos_loss_type: {pos_loss_type}")

    # --- 计算抓手二分类损失 ---
    gripper_loss = F.binary_cross_entropy_with_logits(
        gripper_pred, gripper_target, reduction='none'
    )
    # --- 聚合 ---
    total_loss = pos_ori_loss.mean(dim=-1) + gripper_loss.squeeze(-1)

    if reduction == "mean":
        total_loss = total_loss.mean()
    elif reduction == "sum":
        total_loss = total_loss.sum()
    elif reduction == "none":
        pass
    else:
        raise ValueError(f"Unsupported reduction: {reduction}")

    return total_loss

