benchmark_root: /mnt/project_rlinf/jlchen/code/UniVLA/experiments/robot/libero/libero/libero
bddl_files: /mnt/project_rlinf/jlchen/code/UniVLA/experiments/robot/libero/libero/libero/./bddl_files
init_states: /mnt/project_rlinf/jlchen/code/UniVLA/experiments/robot/libero/libero/libero/./init_files
datasets: /mnt/project_rlinf/jlchen/code/UniVLA/experiments/robot/libero/libero/libero/../datasets
assets: /mnt/project_rlinf/jlchen/code/UniVLA/experiments/robot/libero/libero/libero/./assets
